spin_manifest_version = 2

[application]
name = "geoip"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "geoip"

[component.geoip]
source = "geoip.wasm"
allowed_outbound_hosts = []

[component.geoip.build]
#command = "cargo build --target wasm32-wasip1 --release"
command = "cargo build --target wasm32-wasip1 --release -Z unstable-options --artifact-dir ."
watch = ["src/**/*.rs", "Cargo.toml"]
